version: '3'
services:
  postgres_flext:
    image: postgres:latest
    container_name: postgres_flext
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - flext_net
networks:
  flext_net:
    name: flext_net
